# Generated by Django 4.0.4 on 2022-06-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilename', models.CharField(default='', max_length=122)),
                ('profileemail', models.CharField(default='', max_length=122)),
                ('profilenumber', models.CharField(default='', max_length=122)),
                ('profilecollege', models.CharField(default='', max_length=122)),
                ('branch', models.CharField(default='', max_length=122)),
                ('profiledesc', models.TextField()),
                ('profileimage', models.ImageField(default='', upload_to='home/profile/images')),
            ],
        ),
    ]
