# Generated by Django 4.0.4 on 2022-06-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='collegename',
            new_name='clubname',
        ),
    ]
