# Generated by Django 4.0.4 on 2022-06-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_collegename_event_clubname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilecollege',
            field=models.CharField(default='', max_length=122),
        ),
    ]
