# Generated by Django 4.0.4 on 2022-06-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_profile_profilecollege'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profilecollege',
        ),
    ]
