# Generated by Django 4.0.4 on 2022-06-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_eventlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlogin',
            name='event_name',
            field=models.CharField(default='', max_length=122),
        ),
    ]
